// Generated by CoffeeScript 1.10.0
(function() {
  var Bot, File, Message, bot;

  Bot = require('telegram-api');

  Message = require('telegram-api/types/Message');

  File = require('telegram-api/types/File');

  bot = new Bot({
    token: '177337245:AAFgsgSRJU5TkDMvIrOGDZUtN9HjGWpy3ks'
  });

  bot.start();

  bot.get(/Ciao Sabbia/, function(message) {
    var answer, senderName;
    senderName = message.from.first_name;
    answer = new Message().text('Ciao ' + senderName).to(message.chat.id);
    console.log(message);
    return bot.send(answer);
  });

  bot.get(/Sabbia, cena da te sta sera?/, function(message) {
    var answer, risposta, senderName;
    senderName = message.from.first_name;
    risposta = 'Cazzo ' + senderName + '\nBella idea! Fatta.. Vi aspetto alle 21';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, In irlanda tanta birra?/, function(message) {
    var answer, risposta;
    risposta = 'Mah.. Birra insomma.. Figa tantissima!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, ma sei ancora incazzato?/, function(message) {
    var answer, risposta;
    risposta = 'Quel sordo del cazzo, se lo trovo gli spacco le gambe!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, hai chiamto il boa?/, function(message) {
    var answer, risposta;
    risposta = 'Quel sordo di merda!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, come va?/, function(message) {
    var answer, risposta;
    risposta = 'Fatti i cazzi tuoi stronzo!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, ma la ross come sta?/, function(message) {
    var answer, risposta;
    risposta = 'Guarda.. A parte il riso non so più cosa mi prenda di lei..';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, hai visto Tarolo?/, function(message) {
    var answer, risposta;
    risposta = 'L\'ho visto per strada.. Mamma lo prenderei a schiaffi!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, ci sei sta sera?/, function(message) {
    var answer, risposta;
    risposta = 'No, vado a farmi inculare';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, cosa fai sta sera?/, function(message) {
    var answer, risposta;
    risposta = 'Guardo Harry Potter coglione';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, esci?/, function(message) {
    var answer, risposta;
    risposta = 'C\'è figa? Allora si!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, dai a noi puoi dirlo../, function(message) {
    var answer, risposta;
    risposta = 'ok ok.. è vero.. me la sono portata a letto.. ma avete visto che culo che ha?? non potevo resistere';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

  bot.get(/Sabbia, fai te la macchina?/, function(message) {
    var answer, risposta;
    risposta = 'col cazzo! la metto sempre io porca troia!';
    answer = new Message().text(risposta).to(message.chat.id);
    return bot.send(answer);
  });

}).call(this);
